"""Tests for ForgeBase linting API endpoints."""
from __future__ import annotations

import pytest

from hephaestus.forgebase.domain.enums import (
    ClaimStatus,
    FindingCategory,
    FindingSeverity,
    PageType,
    SupportType,
)


@pytest.fixture
async def vault_with_data(client, forgebase):
    """Create a vault with enough data to lint."""
    resp = await client.post(
        "/api/forgebase/vaults",
        json={"name": "Lint Test Vault", "description": "For lint tests"},
    )
    vault_id = resp.json()["vault_id"]

    from hephaestus.forgebase.domain.values import EntityId

    vid = EntityId(vault_id)

    # Create a page and claim so lint has something to work with
    page, pv = await forgebase.pages.create_page(
        vault_id=vid,
        page_key="concept:lint_target",
        page_type=PageType.CONCEPT,
        title="Lint Target",
        content=b"# Lint Target\nContent.",
    )
    claim, cv = await forgebase.claims.create_claim(
        vault_id=vid,
        page_id=page.page_id,
        statement="An unsupported claim.",
        status=ClaimStatus.SUPPORTED,
        support_type=SupportType.GENERATED,
        confidence=0.5,
    )

    return vault_id, vid, page, claim


@pytest.mark.asyncio
async def test_lint_vault_sse(client, vault_with_data):
    """POST /api/forgebase/vaults/{id}/lint returns SSE stream."""
    vault_id, *_ = vault_with_data
    resp = await client.post(
        f"/api/forgebase/vaults/{vault_id}/lint",
        json={},
    )
    assert resp.status_code == 200
    assert "text/event-stream" in resp.headers["content-type"]
    # Read the full response
    body = resp.text
    assert "event: stage" in body or "event: complete" in body


@pytest.mark.asyncio
async def test_get_lint_report_after_lint(client, forgebase, vault_with_data):
    """GET /api/forgebase/vaults/{id}/lint/report returns report after lint."""
    vault_id, vid, *_ = vault_with_data

    # Run lint directly via engine (not SSE)
    await forgebase.lint_engine.run_lint(vault_id=vid)

    resp = await client.get(f"/api/forgebase/vaults/{vault_id}/lint/report")
    assert resp.status_code == 200
    data = resp.json()
    assert "report_id" in data
    assert "finding_count" in data
    assert "debt_score" in data
    assert "findings_by_category" in data
    assert "findings_by_severity" in data


@pytest.mark.asyncio
async def test_get_lint_report_no_reports(client, vault_with_data):
    """GET /api/forgebase/vaults/{id}/lint/report returns 404 if no reports."""
    vault_id, *_ = vault_with_data
    resp = await client.get(f"/api/forgebase/vaults/{vault_id}/lint/report")
    assert resp.status_code == 404


@pytest.mark.asyncio
async def test_list_findings_after_lint(client, forgebase, vault_with_data):
    """GET /api/forgebase/vaults/{id}/lint/findings lists findings."""
    vault_id, vid, *_ = vault_with_data

    # Run lint to generate findings
    await forgebase.lint_engine.run_lint(vault_id=vid)

    resp = await client.get(f"/api/forgebase/vaults/{vault_id}/lint/findings")
    assert resp.status_code == 200
    data = resp.json()
    assert "findings" in data
    assert "count" in data
    assert isinstance(data["findings"], list)


@pytest.mark.asyncio
async def test_list_findings_with_filter(client, forgebase, vault_with_data):
    """GET /api/forgebase/vaults/{id}/lint/findings?severity=critical filters."""
    vault_id, vid, *_ = vault_with_data
    await forgebase.lint_engine.run_lint(vault_id=vid)

    resp = await client.get(
        f"/api/forgebase/vaults/{vault_id}/lint/findings",
        params={"severity": "critical"},
    )
    assert resp.status_code == 200
    data = resp.json()
    # All returned findings should be critical
    for f in data["findings"]:
        assert f["severity"] == "critical"


@pytest.mark.asyncio
async def test_triage_finding(client, forgebase, vault_with_data):
    """POST .../lint/findings/{id}/triage updates the remediation route."""
    vault_id, vid, *_ = vault_with_data

    # Run lint to create findings
    report = await forgebase.lint_engine.run_lint(vault_id=vid)

    # Get findings
    resp = await client.get(f"/api/forgebase/vaults/{vault_id}/lint/findings")
    data = resp.json()

    if data["count"] == 0:
        pytest.skip("No findings generated by lint detectors")

    finding_id = data["findings"][0]["finding_id"]

    # Triage the finding
    triage_resp = await client.post(
        f"/api/forgebase/vaults/{vault_id}/lint/findings/{finding_id}/triage",
        json={"remediation_route": "research_only"},
    )
    assert triage_resp.status_code == 200
    triage_data = triage_resp.json()
    assert triage_data["remediation_route"] == "research_only"
    assert triage_data["remediation_status"] == "triaged"


@pytest.mark.asyncio
async def test_triage_finding_invalid_route(client, forgebase, vault_with_data):
    """POST .../lint/findings/{id}/triage with invalid route returns 400."""
    vault_id, vid, *_ = vault_with_data
    await forgebase.lint_engine.run_lint(vault_id=vid)

    resp = await client.get(f"/api/forgebase/vaults/{vault_id}/lint/findings")
    data = resp.json()

    if data["count"] == 0:
        pytest.skip("No findings generated by lint detectors")

    finding_id = data["findings"][0]["finding_id"]

    triage_resp = await client.post(
        f"/api/forgebase/vaults/{vault_id}/lint/findings/{finding_id}/triage",
        json={"remediation_route": "not_a_valid_route"},
    )
    assert triage_resp.status_code == 400
    assert "Invalid remediation route" in triage_resp.json()["detail"]
