"""Public lens-system exports."""

from hephaestus.lenses.bundles import (
    BundleCandidate,
    BundleComposer,
    BundleProof,
    BundleRecomposition,
    BundleSelectionResult,
    BundleValidationResult,
    CompatibilityEvidence,
    FoldState,
    RuntimeBundleProof,
    build_bundle_candidates,
    build_fold_state,
)
from hephaestus.lenses.cards import LensCard, SpanRef, compile_lens_card, score_query_against_card
from hephaestus.lenses.cells import (
    CohesionCell,
    CohesionCellIndex,
    LensMembership,
    RuntimeCohesionCell,
    RuntimeFoldState,
    RuntimeReferenceState,
    build_cohesion_cell,
    build_reference_state,
    build_runtime_fold_state,
)
from hephaestus.lenses.exclusion_ledger import (
    AdaptiveExclusionLedger,
    DomainFatigueRecord,
    LedgerDecision,
    LedgerEvent,
)
from hephaestus.lenses.guards import GuardCheck, HandoffGuardResult, evaluate_handoff_guards
from hephaestus.lenses.lineage import (
    LensLineage,
    LineageSource,
    LineageValidationResult,
    build_composite_lineage,
    build_lineage_token,
    build_native_lineage,
    compute_reference_signature,
    lineage_from_bundle_proof,
    lineage_from_singleton,
    validate_lineage,
    validate_lineages,
)
from hephaestus.lenses.loader import (
    Lens,
    LensLoader,
    LensValidationError,
    StructuralPattern,
)
from hephaestus.lenses.selector import (
    EmbeddingModel,
    LensScore,
    LensSelector,
    SelectionPlan,
)
from hephaestus.lenses.state import (
    CompositeLens,
    GuardDecision,
    InvalidationEvent,
    LensBundleMember,
    LensBundleProof,
    LensEngineState,
    RecompositionEvent,
    ResearchReferenceArtifact,
    ResearchReferenceState,
)

__all__ = [
    "AdaptiveExclusionLedger",
    "BundleCandidate",
    "BundleComposer",
    "BundleProof",
    "BundleRecomposition",
    "BundleSelectionResult",
    "BundleValidationResult",
    "CohesionCell",
    "CohesionCellIndex",
    "CompatibilityEvidence",
    "CompositeLens",
    "DomainFatigueRecord",
    "EmbeddingModel",
    "FoldState",
    "GuardCheck",
    "GuardDecision",
    "HandoffGuardResult",
    "InvalidationEvent",
    "LedgerDecision",
    "LedgerEvent",
    "Lens",
    "LensBundleMember",
    "LensBundleProof",
    "LensCard",
    "LensEngineState",
    "LensLineage",
    "LensLoader",
    "LensMembership",
    "LensScore",
    "LensSelector",
    "LensValidationError",
    "LineageSource",
    "LineageValidationResult",
    "RecompositionEvent",
    "ResearchReferenceArtifact",
    "ResearchReferenceState",
    "RuntimeBundleProof",
    "RuntimeCohesionCell",
    "RuntimeFoldState",
    "RuntimeReferenceState",
    "SelectionPlan",
    "SpanRef",
    "StructuralPattern",
    "build_bundle_candidates",
    "build_cohesion_cell",
    "build_composite_lineage",
    "build_fold_state",
    "build_lineage_token",
    "build_native_lineage",
    "build_reference_state",
    "build_runtime_fold_state",
    "compile_lens_card",
    "compute_reference_signature",
    "evaluate_handoff_guards",
    "lineage_from_bundle_proof",
    "lineage_from_singleton",
    "score_query_against_card",
    "validate_lineage",
    "validate_lineages",
]
