"""Tests for publication-ready markdown export."""

from __future__ import annotations

from pathlib import Path
from types import SimpleNamespace

import pytest

from hephaestus.export.markdown import ExportConfig, export_markdown, export_to_file
from hephaestus.output.formatter import AlternativeInvention, InventionReport


def _make_report(**overrides) -> InventionReport:
    defaults = dict(
        problem="Load balancer for unpredictable traffic spikes",
        structural_form="allocation under bounded constraints",
        invention_name="Immune-Memory Scheduler",
        source_domain="Immune System",
        domain_distance=0.85,
        structural_fidelity=0.82,
        novelty_score=0.89,
        mechanism="T-cell memory enables rapid recall of successful responses",
        translation="• T-cell receptor → task signature\n• Memory cell → cached plan",
        architecture="Redis-backed immune memory layer with autoscaling hooks",
        where_analogy_breaks="No MHC equivalent for task classification",
        cost_usd=1.23,
        models_used=["claude-opus-4-6"],
        depth=3,
        wall_time_seconds=42.5,
    )
    defaults.update(overrides)
    return InventionReport(**defaults)


class TestExportMarkdown:
    def test_basic_output(self):
        md = export_markdown(_make_report())
        assert "# Immune-Memory Scheduler" in md
        assert "Executive Summary" in md
        assert "Problem Statement" in md

    def test_includes_scores_in_summary(self):
        md = export_markdown(_make_report())
        assert "0.85" in md
        assert "0.82" in md
        assert "0.89" in md

    def test_includes_confidence_table(self):
        md = export_markdown(_make_report())
        assert "Confidence Analysis" in md
        assert "Domain Distance" in md
        assert "Far transfer" in md

    def test_includes_roadmap(self):
        md = export_markdown(_make_report())
        assert "Implementation Roadmap" in md
        assert "Validate core mechanism" in md

    def test_includes_limitations(self):
        md = export_markdown(_make_report())
        assert "Known Limitations" in md
        assert "MHC" in md

    def test_footer(self):
        md = export_markdown(_make_report())
        assert "Hephaestus" in md
        assert "Generated by" in md


class TestExportConfig:
    def test_disable_confidence(self):
        cfg = ExportConfig(include_confidence=False)
        md = export_markdown(_make_report(), cfg)
        assert "Confidence Analysis" not in md

    def test_disable_roadmap(self):
        cfg = ExportConfig(include_roadmap=False)
        md = export_markdown(_make_report(), cfg)
        assert "Implementation Roadmap" not in md

    def test_include_cost(self):
        cfg = ExportConfig(include_cost=True)
        md = export_markdown(_make_report(), cfg)
        assert "Generation Metadata" in md
        assert "$1.23" in md

    def test_cost_hidden_by_default(self):
        md = export_markdown(_make_report())
        assert "Generation Metadata" not in md

    def test_author_and_title_prefix(self):
        cfg = ExportConfig(author="Dr. Smith", title_prefix="[DRAFT] ")
        md = export_markdown(_make_report(), cfg)
        assert "# [DRAFT] Immune-Memory Scheduler" in md
        assert "Dr. Smith" in md

    def test_date_auto_fill(self):
        cfg = ExportConfig()
        assert len(cfg.date) == 10  # YYYY-MM-DD

    def test_custom_date(self):
        cfg = ExportConfig(date="2026-01-15")
        md = export_markdown(_make_report(), cfg)
        assert "2026-01-15" in md

    def test_alternatives_shown(self):
        report = _make_report(alternatives=[
            AlternativeInvention(
                rank=2,
                invention_name="Ant-Colony Router",
                source_domain="Biology",
                novelty_score=0.75,
                summary="Pheromone-based path optimization",
            )
        ])
        md = export_markdown(report)
        assert "Alternative Approaches" in md
        assert "Ant-Colony Router" in md

    def test_alternatives_hidden(self):
        cfg = ExportConfig(include_alternatives=False)
        report = _make_report(alternatives=[
            AlternativeInvention(rank=2, invention_name="X", source_domain="Y", novelty_score=0.5)
        ])
        md = export_markdown(report, cfg)
        assert "Alternative Approaches" not in md

    def test_research_sections_render(self):
        report = _make_report(
            baseline_dossier=SimpleNamespace(summary="Token buckets are common.", keywords_to_avoid=["retry with backoff"]),
            external_grounding_report=SimpleNamespace(summary="Adaptive routing systems are adjacent.", closest_related_work=["Project X"]),
            implementation_risk_review=SimpleNamespace(summary="Feedback oscillation is the main risk.", major_risks=["oscillation"]),
        )
        md = export_markdown(report)
        assert "State of the Art Recon" in md
        assert "External Grounding" in md
        assert "Implementation Risk Review" in md


class TestExportToFile:
    def test_writes_markdown(self, tmp_path: Path):
        path = tmp_path / "report.md"
        export_to_file(_make_report(), path)
        assert path.exists()
        content = path.read_text()
        assert "Immune-Memory Scheduler" in content

    def test_writes_json(self, tmp_path: Path):
        path = tmp_path / "report.json"
        export_to_file(_make_report(), path)
        content = path.read_text()
        assert "Immune-Memory Scheduler" in content

    def test_creates_parent_dirs(self, tmp_path: Path):
        path = tmp_path / "deep" / "nested" / "report.md"
        export_to_file(_make_report(), path)
        assert path.exists()
